---
title: "2021 Calendar"
author: "Georgetown College Cross Country"
date: "Updated:`r Sys.time()`"
output:
  rmdformats::readthedown:
    highlight: kate
    toc_depth:  4
    css: style.css
---


```{r include=FALSE}
require(knitr)
require(mosaic)
require(DT)
require(kableExtra)
library(xtable)
library(readxl)
library(rJava)
library(xlsx)
```

# Calendar

## Select a month below... {.tabset}

### August


```{r echo=FALSE, results='asis'}

data <- read.xlsx2("Schedule.xlsx",sheetIndex=1,
                  colClasses=c("Date","character","character","character"))
aug <- data[data$Date<as.Date("2021-09-01"),]
aug[,1]=as.character(aug[,1])
print(xtable(aug),type='html',include.rownames=FALSE)
```

### September

```{r echo=FALSE, results='asis'}

sept <- data[data$Date<as.Date("2021-10-01") & data$Date>as.Date("2021-08-31"),]
sept[,1]=as.character(sept[,1])
print(xtable(sept),type='html',include.rownames=FALSE)
```

### October

```{r echo=FALSE, results='asis'}

oct <- data[data$Date<as.Date("2021-11-01") & data$Date>as.Date("2021-09-30"),]
oct[,1]=as.character(oct[,1])
print(xtable(oct),type='html',include.rownames=FALSE)
```

### November

```{r echo=FALSE, results='asis'}

nov <- data[data$Date<as.Date("2021-12-01") & data$Date>as.Date("2021-10-31"),]
nov[,1]=as.character(nov[,1])
print(xtable(nov),type='html',include.rownames=FALSE)
```

### Meets

```{r echo=FALSE, results='asis'}

meets <- data[data$Type=="Meet",]
meets[,1]=as.character(meets[,1])
print(xtable(meets),type='html',include.rownames=FALSE)
```

