---
title: "JEnna Strong Fall Classic Information"
author: "Luke Garnett"
date: "Updated:`r Sys.time()`"
output:
  rmdformats::readthedown:
    highlight: kate
    toc_depth:  4
    css: style.css
---

```{r include=FALSE}
require(knitr)
require(mosaic)
require(DT)
library(xtable)
```

## Information

<a href="2021_JennaStrong_Fall_Classic_Meet_Information.pdf" target="_blank" class="btn btn-lg btn-outline">
    <i class="fa fa-file-pdf-o"></i>
    Download file
</a>

[Live Results](http://live.finishtiming.com/meets/440268/events) \

[Finish Line Video **TENTATIVE**](https://boxcast.tv/view/jennastrong-fall-classic-finish-line-733313)


## Maps

[Men's 8k](http://www.wilmingtonquakers.com/sports/mxc/Men-s_8-Kilometer_Course.pdf) \

[Women's 5k](http://www.wilmingtonquakers.com/sports/wxc/Women-s_5-Kilometer_Course.pdf)

## Timeline

- 12:00pm | Load Bus at Stadium
- 12:15pm | Depart for Wilmington College
- 3:00pm | Arrive at Wilmington, College
- 4:30pm | Women's 5k
- 5:15pm | Men's 8k
- 7:00pm | Depart for home

## Teams

- Anderson (Ind.) (W)
- Anderson (Ind.) (M)
- Ashland (W)
- Ashland (M)
- Berea (W)
- Berea (M)
- Capital (M)
- Cedarville (M)
- Centre (W)
- Centre (M)
- Earlham (W)
- Earlham (M)
- Franklin (W)
- Franklin (M)
- Georgetown (Ky.) (W)
- Georgetown (Ky.) (M)
- Hanover (W)
- Hanover (M)
- Heidelberg (W)
- Heidelberg (M)
- Hocking College (W)
- Hocking College (M)
- Indiana East (W)
- Indiana East (M)
- Indiana Kokomo (W)
- Indiana Kokomo (M)
- Kenyon (W)
- Kenyon (M)
- Lindsey Wilson (W)
- Lindsey Wilson (M)
- Marietta (W)
- Marietta (M)
- Mount St. Joseph (W)
- Mount St. Joseph (M)
- Mount Vernon Nazarene (W)
- Mount Vernon Nazarene (M)
- Muskingum (W)
- Muskingum (M)
- Northern Kentucky (W)
- Northern Kentucky (M)
- Ohio Christian (W)
- Ohio Christian (M)
- Ohio Dominican (W)
- Ohio Dominican (M)
- Ohio State Running Club (W)
- Ohio State Running Club (M)
- Pikeville (W)
- Pikeville (M)
- Shawnee State (W)
- Shawnee State (M)
- Spalding (W)
- Spalding (M)
- Thomas More (W)
- Thomas More (M)
- Transylvania (W)
- Transylvania (M)
- UC Running Club (M)
- Walsh (W)
- Walsh (M)
- Wilmington (Ohio) (W)
- Wilmington (Ohio) (M)
- Wittenberg (W)
- Wittenberg (M)
- Wooster (W)
- Wooster (M)
 	
 